import React,{useEffect,useMemo,useState}from'react';
import{CheckCircle2,Database,Download,FileText,Plus,Save,ShieldCheck,Sparkles}from'lucide-react';
import'./style.css';

type Result={ok:boolean;name?:string;deskUrl?:string;error?:string;submitWarning?:string;user?:string;companies?:any[];items?:any[]};
type Settings={baseUrl:string;company:string;itemCode:string};
type LocalPresets={companies:string[];items:{code:string;label:string}[]};
const SKEY='erpnext-nota-facil-presets-v2',LKEY='erpnext-nota-facil-local-presets-v1';
const emptyS:Settings={baseUrl:'',company:'',itemCode:''};
const emptyL:LocalPresets={companies:[],items:[]};
const brl=(v:number)=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(v||0);
const due=()=>{const d=new Date();d.setDate(d.getDate()+7);return d.toISOString().slice(0,10)};
const load=<T,>(k:string,fallback:T):T=>{try{return{...fallback,...JSON.parse(localStorage.getItem(k)||'{}')}}catch{return fallback}};
async function post(path:string,payload:any):Promise<Result>{const r=await fetch(path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const t=await r.text();try{const d=JSON.parse(t||'{}');return r.ok?d:{ok:false,error:d.error||d.message||`Erro HTTP ${r.status}`}}catch{return{ok:false,error:t||`Erro HTTP ${r.status}`}}}
function Select({label,value,onChange,options}:{label:string;value:string;onChange:(v:string)=>void;options:{value:string;label:string}[]}){return <div className="field"><label>{label}</label><select value={value} onChange={e=>onChange(e.target.value)} required><option value="">Selecione</option>{options.map(o=><option key={o.value} value={o.value}>{o.label}</option>)}</select></div>}

export default function App(){
const[settings,setSettings]=useState<Settings>(emptyS),[local,setLocal]=useState<LocalPresets>(emptyL),[remoteCompanies,setRemoteCompanies]=useState<any[]>([]),[remoteItems,setRemoteItems]=useState<any[]>([]),[newCompany,setNewCompany]=useState(''),[newItemCode,setNewItemCode]=useState(''),[newItemLabel,setNewItemLabel]=useState(''),[customerName,setCustomerName]=useState(''),[customerEmail,setCustomerEmail]=useState(''),[qty,setQty]=useState(1),[rate,setRate]=useState(0),[dueDate,setDueDate]=useState(due()),[description,setDescription]=useState(''),[submit,setSubmit]=useState(true),[loading,setLoading]=useState(false),[loadingOptions,setLoadingOptions]=useState(false),[result,setResult]=useState<Result|null>(null);
useEffect(()=>{setSettings(load(SKEY,emptyS));setLocal(load(LKEY,emptyL))},[]);
const total=useMemo(()=>Number(qty||0)*Number(rate||0),[qty,rate]);
const setS=(k:keyof Settings,v:string)=>setSettings(p=>({...p,[k]:v}));
const companyNames=Array.from(new Set([...local.companies,...remoteCompanies.map(c=>c.name).filter(Boolean)]));
const companyOptions=companyNames.map(x=>({value:x,label:x}));
const itemMap=new Map<string,string>();local.items.forEach(i=>itemMap.set(i.code,i.label||i.code));remoteItems.forEach(i=>itemMap.set(i.item_code||i.name,i.item_name||i.item_code||i.name));
const itemOptions=Array.from(itemMap.entries()).map(([value,label])=>({value,label}));
function persist(next:LocalPresets){setLocal(next);localStorage.setItem(LKEY,JSON.stringify(next))}
function addCompany(){const v=newCompany.trim();if(!v)return;persist({...local,companies:Array.from(new Set([...local.companies,v]))});setS('company',v);setNewCompany('');setResult({ok:true,user:'Empresa adicionada aos presets locais.'})}
function addItem(){const code=newItemCode.trim();if(!code)return;const label=newItemLabel.trim()||code;persist({...local,items:[...local.items.filter(i=>i.code!==code),{code,label}]});setS('itemCode',code);setNewItemCode('');setNewItemLabel('');setResult({ok:true,user:'Item adicionado aos presets locais.'})}
function saveSelection(){localStorage.setItem(SKEY,JSON.stringify(settings));setResult({ok:true,user:'Seleção salva neste aparelho.'})}
async function loadOptions(){setLoadingOptions(true);setResult(null);try{const d=await post('/api/options',{baseUrl:settings.baseUrl});if(!d.ok){setResult(d);return}setRemoteCompanies(d.companies||[]);setRemoteItems(d.items||[]);setResult({ok:true,user:`Carregado: ${d.companies?.length||0} empresa(s) e ${d.items?.length||0} item(ns).`})}finally{setLoadingOptions(false)}}
async function generate(e:React.FormEvent){e.preventDefault();setLoading(true);setResult(null);try{setResult(await post('/api/invoices',{baseUrl:settings.baseUrl,company:settings.company,itemCode:settings.itemCode,customerName,customerType:'Individual',email:customerEmail,qty,rate,dueDate,description,submit}))}finally{setLoading(false)}}
const pdf=result?.name?`/api/pdf?name=${encodeURIComponent(result.name)}${settings.baseUrl?`&baseUrl=${encodeURIComponent(settings.baseUrl)}`:''}`:'';
return <main className="container">
<section className="hero"><div><span className="badge"><Sparkles size={16}/> Nota Fácil com ERPNext</span><h1>Selecione a empresa, selecione o item, digite o valor e gere a nota.</h1><p className="lead">Cadastre os presets uma vez e depois apenas selecione.</p><div className="actions"><button className="btn secondary" type="button" onClick={loadOptions} disabled={loadingOptions}><Database size={18}/>{loadingOptions?'Carregando...':'Carregar do ERPNext'}</button></div></div><aside className="heroCard"><div><div className="metric"><span>Empresas</span><strong>{companyOptions.length}</strong></div><div className="metric"><span>Itens</span><strong>{itemOptions.length}</strong></div><div className="metric"><span>Credenciais expostas</span><strong>0</strong></div></div><div className="status ok"><ShieldCheck size={18}/>API Key somente no backend</div></aside></section>
<section className="panel companyPanel"><div className="sectionTitle"><h2>Presets locais</h2><div className="step">A</div></div><p className="panelIntro">Use o nome exato da empresa e o código exato do item no ERPNext.</p><div className="formGrid"><div className="field"><label>Empresa</label><input value={newCompany} onChange={e=>setNewCompany(e.target.value)} placeholder="Ex: Barão da Cunha"/></div><div className="field actions"><button className="btn secondary" type="button" onClick={addCompany}><Plus size={18}/>Adicionar empresa</button></div><div className="field"><label>Código do item</label><input value={newItemCode} onChange={e=>setNewItemCode(e.target.value)} placeholder="Ex: CARNEIRO-HIDRAULICO"/></div><div className="field"><label>Nome para exibição</label><input value={newItemLabel} onChange={e=>setNewItemLabel(e.target.value)} placeholder="Ex: Carneiro Hidráulico"/></div></div><button className="btn secondary" type="button" onClick={addItem}><Plus size={18}/>Adicionar item</button></section>
<section className="grid"><form className="panel" onSubmit={generate}><div className="sectionTitle"><h2>Gerar nota</h2><div className="step">1</div></div><div className="formGrid"><div className="field full"><label>URL do ERPNext</label><input value={settings.baseUrl} onChange={e=>setS('baseUrl',e.target.value)} placeholder="Opcional se configurada na Vercel"/></div><Select label="Empresa" value={settings.company} onChange={v=>setS('company',v)} options={companyOptions}/><Select label="Item" value={settings.itemCode} onChange={v=>setS('itemCode',v)} options={itemOptions}/><div className="field full"><label>Cliente</label><input value={customerName} onChange={e=>setCustomerName(e.target.value)} required/></div><div className="field full"><label>E-mail</label><input value={customerEmail} onChange={e=>setCustomerEmail(e.target.value)} type="email"/></div><div className="field"><label>Quantidade</label><input value={qty} onChange={e=>setQty(Number(e.target.value))} type="number" min="0.01" step="0.01" required/></div><div className="field"><label>Valor unitário</label><input value={rate} onChange={e=>setRate(Number(e.target.value))} type="number" min="0.01" step="0.01" required/></div><div className="field"><label>Vencimento</label><input value={dueDate} onChange={e=>setDueDate(e.target.value)} type="date" required/></div><div className="field"><label>Submeter?</label><select value={submit?'yes':'no'} onChange={e=>setSubmit(e.target.value==='yes')}><option value="yes">Sim</option><option value="no">Não</option></select></div><div className="field full"><label>Descrição</label><textarea value={description} onChange={e=>setDescription(e.target.value)} rows={3}/></div></div><div className="actions"><button className="btn secondary" type="button" onClick={saveSelection}><Save size={18}/>Salvar seleção</button><button className="btn primary" disabled={loading}><CheckCircle2 size={18}/>{loading?'Gerando...':'Gerar nota'}</button></div></form><aside className="side"><div className="result preview"><h3>Prévia</h3><p><b>Empresa:</b> {settings.company||'—'}</p><p><b>Item:</b> {settings.itemCode||'—'}</p><p><b>Cliente:</b> {customerName||'—'}</p><div className="total"><span>Total</span><b>{brl(total)}</b></div></div><div className="result"><h3>Resultado</h3>{!result&&<p>Adicione os presets, selecione e gere a nota.</p>}{result?.ok&&<><p><b>{result.user||'Nota gerada com sucesso.'}</b></p>{result.name&&<p>Número: <b>{result.name}</b></p>}{result.submitWarning&&<div className="errorBox">{result.submitWarning}</div>}<div className="actions">{result.deskUrl&&<a className="btn secondary" href={result.deskUrl} target="_blank"><FileText size={18}/>Abrir</a>}{pdf&&<a className="btn primary" href={pdf}><Download size={18}/>Baixar PDF</a>}</div></>}{result&&!result.ok&&<div className="errorBox">{result.error}</div>}</div></aside></section></main>}
